# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_label',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='reservations',
            field=models.ManyToManyField(blank=True, to='main.Reservation'),
        ),
    ]
